### ISSUE TITLE
Log "ERROR:BthPS3_GetDeviceName failed (...)" event to event viewer

### ISSUE THREAD

**Issue by Kanuan** [nefarius/BthPS3#90]
The following error is not shown in Windows' Event Viewer BthPS3 logs. It causes BT connection to fail silently. Currently unknown if it's an issue with the BT dongle itself or with BthPS3

![image](https://github.com/nefarius/BthPS3/assets/24910442/afbdd687-8147-40e6-9f8c-35a026b775a4)

**Comment by Kanuan** [comment]
[BthPS3.zip](https://github.com/nefarius/BthPS3/files/12470393/BthPS3.zip)

**Comment by nefarius** [comment]
Will log to event log now, plus I removed the check for string length because even if the result is empty, we only copy the maximum allowed character count, no matter if it contains all zeros or garbage.
