### ISSUE TITLE
Error when trying to install the program

### ISSUE THREAD

**Issue by PaxNotFun** [nefarius/BthPS3#96]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read [the project documentation](https://docs.nefarius.at/projects/) and not found a solution to my problem there
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

I wanted to install the driver to play without having the cable connected, in the pc I want to install it is basically new and the program says that the program is already installed or already exists, I looked for everything and found no trace of the driver or anything, I do not know if it is a bug or something.

### Steps to reproduce

- download the program on a new computer
- open the program as administrator
- the program says it already exists 
- I looked for any trace of the program and did not find it.

I didn't really understand this part 

### Screenshots

<img width="960" alt="image" src="https://github.com/nefarius/BthPS3/assets/96891781/48e6b779-af44-46f4-87f9-5d70278c41f3">
<img width="960" alt="image" src="https://github.com/nefarius/BthPS3/assets/96891781/2c5b5860-ef09-4565-beec-9949162bb339">

### Machine info

**CPU-Architecture:** x64
**Windows version:** Windows 11 23H2
**Software/driver version(s):** v2.8.320

### Any other helpful information

the operating system was completely formatted and everything was removed and reinstalled, the computer is new but it was formatted, before it had the program, but as I mentioned everything was removed.

**Comment by nefarius** [comment]
The solution is in the FAQ, please read next time before opening an issue, thanks.
